########Install docker, pip3, increase mvirtual memory and install ELK container######### 
################ by default location /etc/ansible/  ########

---
 - name: Config elk with Docker
   hosts: elk
   remote_user: sysadmin
   become: true
   tasks:

     - name: install docker.io
       apt:
         force_apt_get: yes
         update_cache: yes
         name: docker.io
         state: present

     - name: Increase virtual memory
       command: sysctl -w vm.max_map_count=262144

     - name: Install python3.pip3
       apt:
         force_apt_get: yes
         name: python3-pip
         state: present

     - name: Install Docker python module
       pip:
         name: docker
         state: present

     - name: download and launch a docker elk container
       docker_container:
         name: elk
         image: sebp/elk:761
         state: started
         published_ports:
           - 5601:5601
           - 9200:9200
           - 5044:5044

     - name: Enable docker service
       systemd:
         name: docker
         enabled: yes
